### ISSUE TITLE
Docker compose using features incompatible with version specified

### ISSUE THREAD

**Issue by jim-counter** [subquery/subql-starter#54]
Recently [checks were added](https://github.com/subquery/subql-starter/pull/46) to the the `docker-compose.yaml` in the SubQuery starter project to ensure that dependent containers are not used before they are ready. These work great and stop a bunch of confusing errors when a user creates a new starter project.

When a user creates a new starter project and follows the published instructions they will see an error message `depends_on contains an invalid type, it should be an array` rather than being able to run up their project successfully.

Unfortunately, the `depends_on` feature these changes use is not available in version 3 of Docker Compose. A discussion on the subject and the reasoning behind removing the feature can be found [here](https://github.com/moby/moby/issues/30404).

Suggestion is to downgrade the version of `docker-compose.yaml` to version 2.1 or use a different strategy to ensure dependent containers are initialised before use.

**Comment by wqsz7xn** [comment]
> When a user creates a new starter project and follows the published instructions they will see an error message depends_on contains an invalid type, it should be an array rather than being able to run up their project successfully.

I've been seeing this a bit but have never been able to reproduce the issue myself with a new project. I've installed docker using the suggested [method](https://docs.docker.com/compose/install/#install-compose-on-linux-systems). What docker-compose version are you on? We will likely bump this back down to spec 2.1 which seems to be a fix.

**Comment by jim-counter** [comment]
Ah, this could be the difference, Checking my notes I can see it was installed on Ubuntu using `sudo apt install docker-compose` but I see the official instructions use a different method. `docker-compose --version` gives me `docker-compose version 1.25.0, build unknown` while the latest appears to be 1.29.2 on their site.

I will spin up a new server and install using the official method and see what happens.

**Comment by ianhe8x** [comment]
Can you also try `docker compose`?

**Comment by jim-counter** [comment]
So I tested the theory and it does appear that installing via `apt` is the root cause. It installs version 1.25.0 which throws an error when parsing the starter `docker-compose.yml`. This can be fixed by uninstalling and following the official install instructions @wqsz7xn has [referenced above](https://github.com/subquery/subql-starter/issues/54#issuecomment-1019617128). This worked for me:

- `sudo apt remove --purge docker-compose`
- `sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`
- `sudo chmod +x /usr/local/bin/docker-compose`

@ianhe8x I will take a look at `docker compose` tonight.

**Comment by jim-counter** [comment]
@ianhe8x just confirmed that the containers come up fine with `docker compose` version 2.2.3.
